default: &default
  DEMOGRAPHICS_DIPLOMA: 'custom.lcf_ZD6EzawTf851IK6BqkKi9PugNKthpgjJotbNc9hMSAu'
  DEMOGRAPHICS_OVER18: 'custom.lcf_4qKJ9VGRB1DYjwFSOnrDBowHD4rxBT6KmS82HqU9uoQ'
  DEMOGRAPHICS_WORK_ELIGIBILITY_USA: 'custom.lcf_A6Wt06IbJVBIWiqgOKWveZjWmd1SJNrExmA6mFse0qT'
  DEMOGRAPHICS_WORK_ELIGIBILITY_COUNTRY: 'custom.lcf_qogMsgZA0BqO8EhNvX7ArkNqSteDR68to4YbYP9uqeX'
  FORUM_ID: 'custom.lcf_lfdvql0X4wl4vWdLawHg0Z02F8mOg62COYzQynsWiws'
  EPICENTER_ID: 'custom.lcf_KKAmJRVPbnDXx5PawPeoMVbtevmzGYxWYM6h4nbRcJk'
  INVITATION_TOKEN: 'custom.lcf_TYIs6589OLrpwJdq3SZN8q4b8bTPcJDDL8BODUlz5WQ'
  PAYMENT_PLAN: 'custom.lcf_B410rIUtklIKHiSrxnQDvocLUp9D3gpuFGxP49Vgtl8'
  AMOUNT_PAID: 'custom.lcf_sXaSO35CeYV0CSLrlxo4s1zKUCIQxAuynB7YsLlt7M8'
  SIGNED_INTERNSHIP_AGREEMENT: 'custom.lcf_mENiBk8e9ZTrPR4UTlDSawoTixlWqHTbeZ70totCyaH'
  COHORT_APPLIED: 'custom.lcf_GrOe1vSEWCpdfHpOaCiEchiYTzlGzg7HpL4rICb2bJh'
  COHORT_STARTING: 'custom.lcf_6Tk6lJghWEfqAcSk45W9k93vF6zZ47jUcrC7cLwTQhh'
  COHORT_CURRENT: 'custom.lcf_GaFl52XxO63XvZZPMuazwOclku4lEHjHP0VXGeplq7h'
  COHORT_PARTTIME: 'custom.lcf_gT90ZgS2D9EQScky5COOXvzpnEdlHLDzAlCVQgAEBIM'
  INTERNSHIP_CLASS: 'custom.lcf_Uhma73rkvzxw7h24fhtnXPfxNYLUPkWckEflCTRykgp'
  DEMOGRAPHICS_BIRTH_DATE: 'custom.lcf_pVGPL0vT6maOxhK3U4GRc4mjzjGWmREWg0nPQzylvCE'
  DEMOGRAPHICS_DISABILITY: 'custom.lcf_xl5OstFwOKZrYWhVtCJNEjrhcFfj0J2hb43MdHOCmiW'
  DEMOGRAPHICS_VETERAN: 'custom.lcf_7C6poq2WtkRq6t9136FwaHjahQmWkb7qgOnlwiFc8Fd'
  DEMOGRAPHICS_EDUCATION: 'custom.lcf_38CfDp4LfSEAuLykjw8kZbQH5ZJwQSbUr95i5vCuADY'
  DEMOGRAPHICS_DEGREE: 'custom.lcf_v2zLOe6ZLM9ridABJMUQCzRUkYAWnVEnIPkjB2d57fJ'
  DEMOGRAPHICS_PREVIOUS_JOB: 'custom.lcf_b6edXV72xgsfp5Dw5qS5fQHihwEb8F4jgmWk6iSTZAD'
  DEMOGRAPHICS_PREVIOUS_SALARY: 'custom.lcf_TjagC1kMBfOiYbULzdgdIelJmMd3wXPyCU2VN6KOyLu'
  DEMOGRAPHICS_SHIRT: 'custom.lcf_lizZuswvOd4k08l8kb3KNVmM38kJMdZuxIwjbdhbS6T'
  DEMOGRAPHICS_GENDER: 'custom.lcf_szuq9CwVhfFYVhdqoTO8VE0nWhbWq5G2eBDRrJXTvan'
  DEMOGRAPHICS_RACE: 'custom.lcf_XLoOAQHg31yBv5xVBJDHnRpQVK7o3oIUy5ng50clwy6'
  DEMOGRAPHICS_AFTER_GRADUATION: 'custom.lcf_gYx5rZSQDiuffAnx2T7NMnn8m85XjdELleg1RcXodzU'
  DEMOGRAPHICS_TIME_OFF: 'custom.lcf_Tpvla2MOt4WF7P6J1UvOs1e1wpgb0fUwFIYMUpX7S3L'
  DEMOGRAPHICS_PRONOUNS: 'custom.lcf_Ao2W8RL1PK6Q7ofjizg13tUmCsUWW5byZjXffliA8Af'
  SSN: 'custom.lcf_dyL6MH1fyoZDutSMeAJqTH27vp2RampGnyioDeHOL7e'
  WITHDRAWAL_DATE: 'custom.lcf_se5gJLcIu02UU85KOqs0c8mjm7FmlBIDlbIViKM0y4e'
  KEYCARD: 'custom.lcf_aCBCdhCvvTd7pVi5w4DGnRaQfR9Qty0juUFjt2v0jxa'
  PROBATION_TEACHER: 'custom.lcf_o99nfvwtWbGdTd4PM65gKFYEupJiWpc91NkQMci3pz7'
  PROBATION_ADVISOR: 'custom.lcf_ChZmMDqAp32FRcE710ZkhxEAgRmwpPcrt9rkFzE5KBY'

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
